### ISSUE TITLE
Server Incompatibility

### ISSUE THREAD

**Issue by GamerGremlin** [Iteranya/MobTalkerRedux#16]
Attempting to start a server with the mod installed results in a fatal error. I assume this is due to it attempting to use a client exclusive class on a server.

I've included the part of the crash report that I believe is relevant.

`Mod File: /home/container/mods/mobtalkerredux-org.arsparadox.jar
	Failure message: MobTalkerRedux (mobtalkerredux) has failed to load correctly
		java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
	Mod Version: 1.0.5
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.3.7.jar%2369!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
	at org.arsparadox.mobtalkerredux.MobTalkerRedux$RegistryEvents.<clinit>(MobTalkerRedux.java:75) ~[mobtalkerredux-org.arsparadox.jar%23382!/:org.arsparadox] {re:classloading}
	at org.arsparadox.mobtalkerredux.MobTalkerRedux.<init>(MobTalkerRedux.java:39) ~[mobtalkerredux-org.arsparadox.jar%23382!/:org.arsparadox] {re:classloading}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.7.jar%23441!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.7.jar%23440!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}`

**Comment by miku4j** [comment]
The dev ars iteranya is sitting beside me, he didn't bring his laptop or PC and his phone doesn't have his github creds in his phone. He said he'll take note of it. also "Hi," said the dev.

**Comment by Iteranya** [comment]
I'm here
Working on it

**Comment by Iteranya** [comment]
![image](https://github.com/user-attachments/assets/f262759d-39e2-4c39-ae0d-5b2ac01fc5b3)
Welp . . .

Gotta wait...

**Comment by Iteranya** [comment]
:)

I don't know enough about networking, Skill Issue On My Part

Will put this on hold and add Multiplayer Incompatible on Description

That or I will make a version of this mod for Server only (should've gone with this earlier)

We'll see...
